### ISSUE TITLE
Downloads Resources Over HTTP

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/npm-haxe#24]
The NPM audit warning is still active:

https://www.npmjs.com/advisories/177

The updated version points to an HTTPS endpoint (https://build.haxe.org/builds/haxe/), but this forwards onto HTTP URLs for individual packages, such as here:

http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/linux64/

This is a very important issue for NPM users.

**Comment by andyli** [comment]
> The updated version points to an HTTPS endpoint (https://build.haxe.org/builds/haxe/), but this forwards onto HTTP URLs for individual packages

This is not true. Although the https://build.haxe.org html page links to the http://hxbuilds.s3-website-us-east-1.amazonaws.com/, this is independent of the download urls used by npm-haxe. To illustrate, the file url, e.g. https://build.haxe.org/builds/haxe/windows/haxe_2018-10-16_development_ccd7dbd.zip does NOT do any redirect to a http address, but serves the file directly via https. You can check it by 
```bash
curl -v https://build.haxe.org/builds/haxe/windows/haxe_2018-10-16_development_ccd7dbd.zip -o /dev/null
```

I believe the actual problem here is that npm haven't updated their advisory info regarding to the haxe package.

**Comment by jgranick** [comment]
Submitting a new report (or the form for it) shows a timeline on the right:

![image](https://user-images.githubusercontent.com/833997/47043243-fe0acc00-d141-11e8-80c9-4fb891b2654f.png)

Is there someone who received an email from NPM, that perhaps has a way to try and resolve the security advisory?

**Comment by jgranick** [comment]
Unresolved, using Haxe with NPM results in messages like this (or scarier sounding)


![image](https://user-images.githubusercontent.com/833997/47043348-4629ee80-d142-11e8-8fd8-0aca00f563e0.png)

**Comment by jgranick** [comment]
Maybe this helps: https://www.npmjs.com/policies/security#security-point-of-contact

**Comment by andyli** [comment]
@damoebius Did you receive any email from npm? Can you follow it up?

**Comment by damoebius** [comment]
Mmm i'll have a look on my emails

**Comment by damoebius** [comment]
Well, i'm sorry but i got nothing :(

**Comment by jgranick** [comment]
I contacted them by email, and they resolved it by hand. Thanks everyone :smile:

https://www.npmjs.com/advisories/177
