### ISSUE TITLE
Failed to install from npm

### ISSUE THREAD

**Issue by damoebius** [HaxeFoundation/npm-haxe#6]
Damned it doesn't work :(
I hope that noone will update their project to 4.0.0.

My use case :
- clone taminahx https://github.com/damoebius/taminahx.git
- update package.json as decrybed here : https://github.com/damoebius/npm-haxe/issues/1
- run npm install 

![0000](https://cloud.githubusercontent.com/assets/4668438/13811774/1caba8bc-eb78-11e5-8eeb-21b5935a6630.JPG)

**Comment by clemos** [comment]
Of course, you need a `build.hxml` file ;)
If you don't have one, then your postinstall should contain something like `haxelib install blabla && haxelib install toto && haxelib install other`, and build should be `haxe -main Main.hx -js test.js`.
That's an example, really, it all depends on how you usually build your project and install your dependencies.

**Comment by damoebius** [comment]
My Bad :)
It's work and i was able to compile my project.
So now, how can i manage haxelib dependencies ? can i declare them in my package.json ?

**Comment by clemos** [comment]
This is really up to you. 
You can either : 

Create an .hxml file, both for building your project (`haxe build.hxml`) and for installing dependencies (`haxelib --always install build.hxml`), for example : 
```
-lib mconsole
-lib msignal
-lib createjs
-main Main
-js tamina.js
```
This is the recommanded way, I think.
See http://haxe.org/manual/haxelib-using-haxe.html

Otherwise, you can install the libs you want manually, for example using NPM's `postinstall`:
```json
"scripts": {
   "postinstall" : "haxelib install mconsole && haxelib install msignal"
}
```
and continue building your project manually via the command line (`haxe -lib mconsole -main Main -js tamina.js`)
This is not really recommended, as you obviously have duplicated dependency declaration.

If your project iteslf is an haxelib, it's usually better to declare dependencies in `haxelib.json`.
http://haxe.org/manual/haxelib-json-dependencies.html

**Comment by damoebius** [comment]
Good news, we upgraded about 50% of our projects to the last npm module :)
Stay tuned

**Comment by clemos** [comment]
Great :)
